### ISSUE TITLE
zero knowledge range proof

### ISSUE THREAD

**Issue by omershlo** [mortendahl/rust-paillier#18]
A zk range proof in which the prover and verifier posses common paillier ciphertext and the prover proves that the decrypted ciphertext is in a certain range. The complete proof as well as reference to the original proof and security proof can be found in https://eprint.iacr.org/2017/552.pdf , Appendix A.

As part of this proof we need to add functionalities : "encrypt_with_chosen_randomness" and "encrypt_with_precomputed_randomness"

**Comment by mortendahl** [comment]
I've started some work on `encrypt_with_chosen_randomness` and `encrypt_with_chosen_randomness` but won't have much time this week (away on vacation). Feel free to go ahead!

**Comment by mortendahl** [comment]
@omershlo can we close this one?

**Comment by omershlo** [comment]
👍
