### ISSUE TITLE
zero knowledge proof for encryption of same value under two different keys

### ISSUE THREAD

**Issue by omershlo** [mortendahl/rust-paillier#62]
Statement is `C1, C2`. Prover wants to prove knowledge of `x,r1,r2` such that 
`C1 = (1+N1)^x *r1^N1 mod N1^2` and `C2 = (1+N2)^x *r2^N2 mod N2^2`:

prover first message: choose `alpha, r3, r4`,  where `0<= alpha < min(N1,N2)`, `0<r3< N1`, `0<r4< N2` compute: 
`D1= (1+N1)^alpha *r3^N1 mod N1^2` and `D2 = (1+N2)^alpha *r4^N2 mod N2^2`,
send `D1,D2`

verifier sends a random challenge `e`

prover computes: `z = alpha + ex`, `s1 = r3r1^e mod N1`, `s2 = r4r2^e mod N2`
sends `z,s1,s2` 

verifier checks: 
`Enc_N1(z1 mod N1, s1) = C1^e*D1`
`Enc_N2(z1 mod N2, s2) = C2^e*D2`

**Comment by omershlo** [comment]
The above protocol works for |alpha| >> |ex|

**Comment by rogermb** [comment]
Hi @omershlo! Sorry about the comment on this ancient issue.
I used the zero-knowledge proof you described here in one of my projects, and I want to give proper credit where credit is due.
Do you still remember if you copied this proof from some other publication that I could cite, or did you come up with this elegant proof yourself? 😄
