### ISSUE TITLE
Ciphertext-Plaintext addition

### ISSUE THREAD

**Issue by haochenuw** [mortendahl/rust-paillier#69]
Hi! New to rust and I saw that the library implements adding a ciphertext with a plaintext. However, the following code reports an error: 

```
  let c1 = Paillier::encrypt(&ek, 10);

  let p1 = RawPlaintext::from(BigInt::from(20));

  // add all of them together
  let c = Paillier::add(&ek, &c1, &p1);
```
and it says 
> 16 |   let c = Paillier::add(&ek, &c1, &p1);
   |           ^^^^^^^^^^^^^ the trait `paillier::Add<EncryptionKey, &EncodedCiphertext<u64>, &paillier::RawPlaintext<'_>, _>` is not implemented for `paillier::Paillier`

Could you kindly advise on how I can add a plaintext to a ciphertext in this library? Thanks!

**Comment by haochenuw** [comment]
Found a code snippet that works for `u64` plaintexts! I guess the question really is how to enable plaintexts that has more than 64 bits. Is this supported?

**Comment by omershlo** [comment]
Hi @haochenuw , 
thank you for your question.

here is a test that works for BigInt : https://github.com/ZenGo-X/rust-paillier/blob/master/src/core.rs#L565-L574 
(the ZenGo-X fork is a few commits ahead of this repo )

**Comment by haochenuw** [comment]
Thanks! I'll try out the fork you mentioned.
