### ISSUE TITLE
tests for encrypt with dk? 

### ISSUE THREAD

**Issue by haochenuw** [mortendahl/rust-paillier#70]
I saw in the benchmarks there are two options for encryption: one takes an "ek" and the other takes a "dk". It seems the dk version is faster. However, I didn't find the dk version of the encryption used anywhere else. Is it possible to add examples / tests for it? 

I am on the ZenGo fork. Somehow I couldn't find a "submit issue" button on the homepage of the fork in github. So I posted the issue here.

**Comment by omershlo** [comment]
using dk for encryption is a cool optimisation. 
The interface to use it is the same as for regular encryption just replace EncryptionKey with DecryptionKey. 
https://github.com/mortendahl/rust-paillier/blob/master/src/core.rs#L237 

What kind of tests/examples are you interested in? it should be straight forward 
(note that in general, the encryptor do not need to know to decryption key. The above optimisations works in the special case that the encryptor is also the one who generated the keys )

**Comment by haochenuw** [comment]
Sounds good. I just thought there should be unit tests for this optimisation.
